_core:
  default_config_hash: g5ZsZ18mt8ec49n4-SEpqJxc4rR6fpaWc5qkJ7bgEl4
langcode: es
metadata_etag: '"nZG0Kl07CGmhM7WaGCmM9NihXnFmmHwOXKr0eCE_TTo/idhGwQyvJlFd_VHCiT1o8M9XhU8"'
metadata_last_time: '1716689880'
