pasarela_de_pago_es.stripe:
  type: commerce_payment_gateway_configuration
  mapping:
    publishable_key:
      type: string
      label: 'Publishable key'
    private_key:
      type: string
      label: 'Private key'

