_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
langcode: es
smtp_on: true
smtp_host: smtp.titan.email
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_autotls: true
smtp_timeout: 30
smtp_username: informacion@easyshop.com.mx
smtp_password: 'w"YN1la,}2|$''!b'
smtp_from: informacion@easyshop.com.mx
smtp_fromname: 'Easy Shop'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: true
smtp_test_address: fabricio.hernandez@udg.mx
smtp_reroute_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
smtp_debug_level: 1
